name = "thecollabify-frontend"
pages_build_output_dir = "dist"

[vars]
VITE_API_URL = "https://api.thecollabify.tech/api"
VITE_SOCKET_URL = "wss://api.thecollabify.tech"
VITE_GOOGLE_CLIENT_ID = "223460533138-nkmmomsvj3nvjd8geg77gdp2rqho3o22.apps.googleusercontent.com"
